services:
  postgres_db:
    image: postgres:16
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: freefiregovno999
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: